<?php

use Illuminate\Database\Seeder;

class FieldGroupsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('field_groups')->delete();
        
        \DB::table('field_groups')->insert(array (
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 35121537280887,
                'id' => 1,
                'lft' => 1,
                'rgt' => 2,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-09-25 06:55:40',
                'updated_at' => '2018-09-25 06:55:44',
                'anchor_text' => 'Vesti - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 34351537526604,
                'id' => 2,
                'lft' => 3,
                'rgt' => 4,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-09-25 06:58:45',
                'updated_at' => '2018-09-25 06:58:48',
                'anchor_text' => 'Komorske usluge - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 33571537279684,
                'id' => 3,
                'lft' => 5,
                'rgt' => 6,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-09-25 06:59:31',
                'updated_at' => '2018-09-25 06:59:34',
                'anchor_text' => 'Vrsta Vesti - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 33191537526107,
                'id' => 4,
                'lft' => 7,
                'rgt' => 8,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-09-25 06:59:41',
                'updated_at' => '2018-09-25 06:59:44',
                'anchor_text' => 'Kategorije komorskih usluga - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 32371537279875,
                'id' => 5,
                'lft' => 9,
                'rgt' => 10,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-09-25 06:59:49',
                'updated_at' => '2018-09-25 06:59:52',
                'anchor_text' => 'Sektori - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 33071537796017,
                'id' => 6,
                'lft' => 11,
                'rgt' => 12,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-09-25 10:10:26',
                'updated_at' => '2018-09-25 10:10:28',
                'anchor_text' => 'Uspesne Price - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 34151537794615,
                'id' => 7,
                'lft' => 13,
                'rgt' => 14,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-09-25 10:10:46',
                'updated_at' => '2018-09-25 10:10:48',
                'anchor_text' => 'Price - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 33681537793334,
                'id' => 8,
                'lft' => 15,
                'rgt' => 16,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-09-25 10:10:56',
                'updated_at' => '2018-09-25 10:10:58',
                'anchor_text' => 'Preduzetnici - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 34791537960620,
                'id' => 9,
                'lft' => 17,
                'rgt' => 18,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-09-26 09:17:55',
                'updated_at' => '2018-09-26 09:17:57',
                'anchor_text' => 'Vrsta Dogadjaja - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 34321537961184,
                'id' => 10,
                'lft' => 19,
                'rgt' => 20,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-09-26 09:27:34',
                'updated_at' => '2018-09-26 09:27:36',
                'anchor_text' => 'Oblast - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 35151537962363,
                'id' => 12,
                'lft' => 21,
                'rgt' => 22,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-09-26 09:46:45',
                'updated_at' => '2018-09-26 11:40:25',
                'anchor_text' => 'Prioriteti - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 31641537963919,
                'id' => 13,
                'lft' => 23,
                'rgt' => 24,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-09-26 10:13:04',
                'updated_at' => '2018-09-26 11:40:25',
                'anchor_text' => 'Velicine Firme - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Kontakt Mediji',
                'module_id' => 33881537965719,
                'id' => 14,
                'lft' => 25,
                'rgt' => 26,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-09-26 10:44:17',
                'updated_at' => '2018-09-26 11:40:25',
                'anchor_text' => 'Dogadjaji - Kontakt Mediji',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Kontakt Ucesnici',
                'module_id' => 33881537965719,
                'id' => 15,
                'lft' => 27,
                'rgt' => 28,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-09-26 10:44:43',
                'updated_at' => '2018-09-26 11:40:25',
                'anchor_text' => 'Dogadjaji - Kontakt Ucesnici',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 33881537965719,
                'id' => 16,
                'lft' => 29,
                'rgt' => 30,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-09-26 10:45:05',
                'updated_at' => '2018-09-26 11:40:25',
                'anchor_text' => 'Dogadjaji - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 32111538130850,
                'id' => 17,
                'lft' => 31,
                'rgt' => 32,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-09-28 08:35:39',
                'updated_at' => '2018-09-28 08:35:41',
                'anchor_text' => 'Saopstenja - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 34311538480567,
                'id' => 18,
                'lft' => 33,
                'rgt' => 34,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-10-02 09:43:32',
                'updated_at' => '2018-10-02 09:43:33',
                'anchor_text' => 'Privredna drustva clana udruzenja - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 36291538481832,
                'id' => 19,
                'lft' => 35,
                'rgt' => 36,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-10-02 10:04:31',
                'updated_at' => '2018-10-02 10:04:33',
                'anchor_text' => 'Udruzenja - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 34471538483698,
                'id' => 20,
                'lft' => 37,
                'rgt' => 38,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-10-02 10:40:10',
                'updated_at' => '2018-10-02 10:40:12',
                'anchor_text' => 'Grupacije udruzenja - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 33151538484374,
                'id' => 21,
                'lft' => 39,
                'rgt' => 40,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-10-02 10:47:05',
                'updated_at' => '2018-10-02 10:47:07',
                'anchor_text' => 'FAQ udruzenja - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 33901538485064,
                'id' => 22,
                'lft' => 41,
                'rgt' => 42,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-10-02 10:58:25',
                'updated_at' => '2018-10-02 10:58:28',
                'anchor_text' => 'Clanovi udruzenja - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 30091537963517,
                'id' => 23,
                'lft' => 43,
                'rgt' => 44,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-10-03 07:53:59',
                'updated_at' => '2018-10-03 07:54:01',
                'anchor_text' => 'Opstine - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 35361537962863,
                'id' => 24,
                'lft' => 45,
                'rgt' => 46,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-10-03 09:00:35',
                'updated_at' => '2018-10-03 09:00:37',
                'anchor_text' => 'Zemlje - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 35571537961651,
                'id' => 25,
                'lft' => 47,
                'rgt' => 48,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-10-03 09:12:19',
                'updated_at' => '2018-10-03 09:12:21',
                'anchor_text' => 'Organizatori - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 33201539331376,
                'id' => 27,
                'lft' => 49,
                'rgt' => 50,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-10-12 06:04:29',
                'updated_at' => '2018-10-12 06:04:45',
                'anchor_text' => 'Regionalne komore - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 34361540561267,
                'id' => 28,
                'lft' => 51,
                'rgt' => 52,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-10-26 13:52:10',
                'updated_at' => '2018-10-26 13:52:12',
                'anchor_text' => ' - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 32391541082305,
                'id' => 29,
                'lft' => 53,
                'rgt' => 54,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-11-01 14:26:38',
                'updated_at' => '2018-11-01 14:26:40',
                'anchor_text' => ' - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Clanarina',
                'module_id' => 34481541087749,
                'id' => 30,
                'lft' => 55,
                'rgt' => 56,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-11-02 07:46:48',
                'updated_at' => '2018-11-02 07:46:50',
                'anchor_text' => ' - Clanarina',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Politika kvaliteta',
                'module_id' => 34481541087749,
                'id' => 31,
                'lft' => 57,
                'rgt' => 58,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-11-02 07:47:12',
                'updated_at' => '2018-11-02 07:47:15',
                'anchor_text' => ' - Politika kvaliteta',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 31481542792682,
                'id' => 32,
                'lft' => 59,
                'rgt' => 60,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-11-21 09:33:05',
                'updated_at' => '2018-11-21 09:33:07',
                'anchor_text' => ' - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 34071542791824,
                'id' => 33,
                'lft' => 61,
                'rgt' => 62,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-11-21 09:33:22',
                'updated_at' => '2018-11-21 09:33:25',
                'anchor_text' => ' - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 35631542790824,
                'id' => 34,
                'lft' => 63,
                'rgt' => 64,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-11-21 09:33:44',
                'updated_at' => '2018-11-21 09:33:46',
                'anchor_text' => ' - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            
            array (
                'name' => 'Engleski prevodi',
                'module_id' => 34321543915793,
                'id' => 35,
                'lft' => 65,
                'rgt' => 66,
                'parent_id' => NULL,
                'depth' => 0,
                'scope_id' => NULL,
                'created_at' => '2018-12-04 09:37:36',
                'updated_at' => '2018-12-04 09:37:39',
                'anchor_text' => ' - Engleski prevodi',
                'anchor_html' => '',
                'slug' => '',
                'created_by' => 1,
                'updated_by' => 1,
            ),
        ));
        
        
    }
}