<?php

use Illuminate\Database\Seeder;

class ModulesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('modules')->delete();
        
        \DB::table('modules')->insert(array (
            
            array (
                'id' => 1,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Users',
                'model_name' => 'User',
                'table_name' => 'users',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{first_name}} {{last_name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-users',
                'reporting' => 1,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2016-04-01 07:17:48',
                'updated_at' => '2018-11-29 08:18:11',
            ),
            
            array (
                'id' => 2,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Invitations',
                'model_name' => 'Invitations',
                'table_name' => 'invitations',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{email}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-envelope-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2016-08-18 06:10:56',
                'updated_at' => '2016-08-18 06:10:56',
            ),
            
            array (
                'id' => 3,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Invitation Statuses',
                'model_name' => 'InvitationStatuses',
                'table_name' => 'invitation_statuses',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-list',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2016-08-18 10:18:07',
                'updated_at' => '2016-08-18 10:18:07',
            ),
            
            array (
                'id' => 4,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Assets',
                'model_name' => 'Assets',
                'table_name' => 'assets',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{file_name}}',
                'anchor_html' => '{{file_name}}',
                'icon' => 'fa fa-file-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2016-08-30 10:01:17',
                'updated_at' => '2018-11-26 11:22:19',
            ),
            
            array (
                'id' => 5,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Roles',
                'model_name' => 'Roles',
                'table_name' => 'roles',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-user-circle-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2016-09-02 10:24:28',
                'updated_at' => '2016-09-02 10:24:28',
            ),
            
            array (
                'id' => 6,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Permissions',
                'model_name' => 'Permissions',
                'table_name' => 'permissions',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-minus-circle',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2016-09-02 10:43:44',
                'updated_at' => '2016-09-02 10:43:44',
            ),
            
            array (
                'id' => 7,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'File Tags',
                'model_name' => 'FileTags',
                'table_name' => 'file_tags',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-tags',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2016-10-07 05:14:34',
                'updated_at' => '2016-10-07 05:14:34',
            ),
            
            array (
                'id' => 8,
                'category' => 0,
                'type' => 'sortable',
                'name' => 'Widgets',
                'model_name' => 'Widgets',
                'table_name' => 'widgets',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-square',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-01-10 21:23:31',
                'updated_at' => '2018-01-11 07:18:51',
            ),
            
            array (
                'id' => 9,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Resized Images',
                'model_name' => 'ResizedImages',
                'table_name' => 'resized_images',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{top_x}},{{top_y}} - {{height}},{{width}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-picture-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2017-06-13 04:41:12',
                'updated_at' => '2017-06-13 04:41:12',
            ),
            
            array (
                'id' => 10,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Image sizes',
                'model_name' => 'ImageSizes',
                'table_name' => 'image_sizes',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-picture-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2017-06-13 04:52:01',
                'updated_at' => '2017-06-13 04:52:01',
            ),
            
            array (
                'id' => 12,
                'category' => NULL,
                'type' => 'multilevel_sortable',
                'name' => 'Galleries',
                'model_name' => 'Galleries',
                'table_name' => 'galleries',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{id}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-camera',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2017-08-20 14:32:56',
                'updated_at' => '2017-08-20 14:32:56',
            ),
            
            array (
                'id' => 13,
                'category' => 12,
                'type' => 'multilevel_sortable',
                'name' => 'Gallery Items',
                'model_name' => 'GalleryItems',
                'table_name' => 'gallery_items',
                'max_depth' => 0,
                'slug' => NULL,
                'anchor_text' => '{{id}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-camera',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2017-08-20 14:33:27',
                'updated_at' => '2017-08-20 14:33:27',
            ),
            
            array (
                'id' => 14,
                'category' => 0,
                'type' => 'sortable',
                'name' => 'Field Groups',
                'model_name' => 'FieldGroups',
                'table_name' => 'field_groups',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{|findModule}} - {{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-square',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-01-10 21:23:31',
                'updated_at' => '2018-01-11 07:18:51',
            ),
            
            array (
                'id' => 30091537963517,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Opstine',
                'model_name' => 'Opstine',
                'table_name' => 'municipalities',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-fa',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-09-26 10:05:17',
                'updated_at' => '2018-10-03 07:54:26',
            ),
            
            array (
                'id' => 31481542792682,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Sadrzaji web strana',
                'model_name' => 'SadrzajiWebStrana',
                'table_name' => 'page_contents',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-files-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-11-21 09:31:22',
                'updated_at' => '2018-11-23 14:22:42',
            ),
            
            array (
                'id' => 31641537963919,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Velicine firme',
                'model_name' => 'VelicineFirme',
                'table_name' => 'company_sizes',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-expand',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-09-26 10:11:59',
                'updated_at' => '2018-10-03 09:26:24',
            ),
            
            array (
                'id' => 32111538130850,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Saopstenja',
                'model_name' => 'Saopstenja',
                'table_name' => 'announcements',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-bullhorn',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-09-28 08:34:10',
                'updated_at' => '2018-10-03 09:27:20',
            ),
            
            array (
                'id' => 32371537279875,
                'category' => NULL,
                'type' => 'sortable',
                'name' => 'Sektori',
                'model_name' => 'Sektori',
                'table_name' => 'sectors',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-09-18 12:11:15',
                'updated_at' => '2018-10-25 14:20:15',
            ),
            
            array (
                'id' => 32391541082305,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Organi',
                'model_name' => 'Organi',
                'table_name' => 'authorities',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-bank',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-11-01 14:25:05',
                'updated_at' => '2018-11-01 14:28:17',
            ),
            
            array (
                'id' => 32411538573169,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Izvori slika',
                'model_name' => 'IzvoriSlika',
                'table_name' => 'photo_sources',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{source}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-file-image-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-10-03 11:26:09',
                'updated_at' => '2018-10-03 11:26:09',
            ),
            
            array (
                'id' => 33071537796017,
                'category' => NULL,
                'type' => 'single_entry',
                'name' => 'Uspesne price',
                'model_name' => 'UspesnePrice',
                'table_name' => 'successful_stories',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{id}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-flag-checkered',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-09-24 11:33:37',
                'updated_at' => '2018-09-25 10:12:10',
            ),
            
            array (
                'id' => 33151538484374,
                'category' => 36291538481832,
                'type' => 'sortable',
                'name' => 'FAQ udruzenja',
                'model_name' => 'FaqUdruzenja',
                'table_name' => 'faq',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{question}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-question-circle',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-10-02 10:46:14',
                'updated_at' => '2018-11-28 14:43:34',
            ),
            
            array (
                'id' => 33191537526107,
                'category' => NULL,
                'type' => 'sortable',
                'name' => 'Kategorije komorskih usluga',
                'model_name' => 'KategorijeKomorskihUsluga',
                'table_name' => 'chamber_service_categories',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-09-21 08:35:07',
                'updated_at' => '2018-10-03 09:29:30',
            ),
            
            array (
                'id' => 33201539331376,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Regionalne komore',
                'model_name' => 'RegionalneKomore',
                'table_name' => 'regional_chambers',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-10-12 06:02:56',
                'updated_at' => '2018-12-06 08:40:17',
            ),
            
            array (
                'id' => 33251540220068,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Pks info event newsletter',
                'model_name' => 'PksInfoEventNewsletter',
                'table_name' => 'event_newsletter',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => '{{|getFormatedCreatedAtDate}}',
                'icon' => 'fa fa-envelope-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-10-22 14:54:28',
                'updated_at' => '2018-10-25 09:02:31',
            ),
            
            array (
                'id' => 33431539869711,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Pks info email newsletter',
                'model_name' => 'PksInfoEmailNewsletter',
                'table_name' => 'email_newsletter',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{id}}',
                'anchor_html' => '{{|getFormatedCreatedAtDate}}',
                'icon' => 'fa fa-envelope-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-10-18 13:35:11',
                'updated_at' => '2018-10-25 09:03:44',
            ),
            
            array (
                'id' => 33571537279684,
                'category' => NULL,
                'type' => 'sortable',
                'name' => 'Vrste vesti',
                'model_name' => 'VrstaVesti',
                'table_name' => 'news_categories',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-09-18 12:08:04',
                'updated_at' => '2018-10-03 09:29:59',
            ),
            
            array (
                'id' => 33681537793334,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Preduzetnici',
                'model_name' => 'Preduzetnici',
                'table_name' => 'entrepreneurs',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{entrepreneur_name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-address-card-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-09-24 10:48:54',
                'updated_at' => '2018-10-03 08:19:34',
            ),
            
            array (
                'id' => 33881537965719,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Dogadjaji',
                'model_name' => 'Dogadjaji',
                'table_name' => 'events',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => '<div class="r"><div class="t">{{title}}</div><div class="i"><b>Unos:</b> {{|getFormatedCreatedAtDate}} <b>ID:</b> {{id}}</div></div>',
                'icon' => 'fa fa-calendar',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-09-26 10:41:59',
                'updated_at' => '2018-11-29 09:48:25',
            ),
            
            array (
                'id' => 33901538485064,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Clanovi',
                'model_name' => 'Clanovi',
                'table_name' => 'members',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{first_name}} {{last_name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-user-circle',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-10-02 10:57:44',
                'updated_at' => '2018-11-28 14:10:57',
            ),
            
            array (
                'id' => 34071542791824,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Kategorije web strana',
                'model_name' => 'KategorijeWebStrana',
                'table_name' => 'page_categories',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-11-21 09:17:04',
                'updated_at' => '2018-11-21 09:35:33',
            ),
            
            array (
                'id' => 34151537794615,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Price',
                'model_name' => 'Price',
                'table_name' => 'stories',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-file-text-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-09-24 11:10:15',
                'updated_at' => '2018-10-03 09:32:30',
            ),
            
            array (
                'id' => 34311538480567,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Privredna drustva clana udruzenja',
                'model_name' => 'PrivrednaDrustvaClanaUdruzenja',
                'table_name' => 'association_member_companies',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-bank',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-10-02 09:42:47',
                'updated_at' => '2018-11-09 08:19:08',
            ),
            
            array (
                'id' => 34321537961184,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Oblasti',
                'model_name' => 'Oblast',
                'table_name' => 'domains',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-folder',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-09-26 09:26:24',
                'updated_at' => '2018-10-03 09:32:59',
            ),
            
            array (
                'id' => 34321543915793,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Dokumenti',
                'model_name' => 'Dokumenti',
                'table_name' => 'documents',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-file-text',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-12-04 09:29:53',
                'updated_at' => '2018-12-04 09:38:48',
            ),
            
            array (
                'id' => 34351537526604,
                'category' => 33191537526107,
                'type' => 'sortable',
                'name' => 'Komorske usluge',
                'model_name' => 'KomorskeUsluge',
                'table_name' => 'chamber_services',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{services}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-briefcase',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-09-21 08:43:24',
                'updated_at' => '2018-12-05 08:59:18',
            ),
            
            array (
                'id' => 34361540561267,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Zakonske regulative',
                'model_name' => 'ZakonskeRegulative',
                'table_name' => 'legislations',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-balance-scale',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-10-26 13:41:07',
                'updated_at' => '2018-11-28 14:26:42',
            ),
            
            array (
                'id' => 34471538483698,
                'category' => 36291538481832,
                'type' => 'sortable',
                'name' => 'Grupacije udruzenja',
                'model_name' => 'GrupacijeUdruzenja',
                'table_name' => 'association_groups',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-users',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-10-02 10:34:58',
                'updated_at' => '2018-11-28 14:44:10',
            ),
            
            array (
                'id' => 34481540191608,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Grupe newsletter pretplatnika',
                'model_name' => 'GrupeNewsletterPretplatnika',
                'table_name' => 'subscriber_groups',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-envelope-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-10-22 07:00:08',
                'updated_at' => '2018-10-22 07:00:08',
            ),
            
            array (
                'id' => 34481541087749,
                'category' => NULL,
                'type' => 'single_entry',
                'name' => 'Privredna komora',
                'model_name' => 'PrivrednaKomora',
                'table_name' => 'chamber_of_commerce',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-university',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-11-01 15:55:49',
                'updated_at' => '2018-12-04 09:49:29',
            ),
            
            array (
                'id' => 34791537960620,
                'category' => NULL,
                'type' => 'sortable',
                'name' => 'Vrste dogadjaja',
                'model_name' => 'VrstaDogadjaja',
                'table_name' => 'event_categories',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-09-26 09:17:00',
                'updated_at' => '2018-10-03 09:33:59',
            ),
            
            array (
                'id' => 34911540190874,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Newsletter pretplatnici',
                'model_name' => 'NewsletterPretplatnici',
                'table_name' => 'subscribers',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{email}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-envelope',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-10-22 06:47:54',
                'updated_at' => '2018-10-22 07:24:59',
            ),
            
            array (
                'id' => 35101540369493,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Tipovi newslettera',
                'model_name' => 'TipoviNewslettera',
                'table_name' => 'newsletter_types',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-10-24 08:24:53',
                'updated_at' => '2018-10-24 08:24:53',
            ),
            
            array (
                'id' => 35121537280887,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Vesti',
                'model_name' => 'Vesti',
                'table_name' => 'news',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => '<div class="l {{|isApproved}}"><img src="/storage/assets/{{|thumbnail}}"></div><div class="r"><div class="t">{{title}}</div><div class="i"><b>Objavljeno:</b> {{|getFormatedPublishDate}} <b>ID:</b> {{id}}</div><div class="i"><b>Unos:</b></div></div>',
                'icon' => 'fa fa-newspaper-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-09-18 12:28:07',
                'updated_at' => '2018-12-05 09:32:31',
            ),
            
            array (
                'id' => 35151537962363,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Prioriteti',
                'model_name' => 'Prioriteti',
                'table_name' => 'priorities',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-exclamation',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-09-26 09:46:03',
                'updated_at' => '2018-10-03 09:35:54',
            ),
            
            array (
                'id' => 35361537962863,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Zemlje',
                'model_name' => 'Zemlje',
                'table_name' => 'countries',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{country_name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-globe',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-09-26 09:54:23',
                'updated_at' => '2018-10-03 09:01:20',
            ),
            
            array (
                'id' => 35511540538858,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Email adrese',
                'model_name' => 'EmailAdrese',
                'table_name' => 'email_adrese',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{email}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-at',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-10-26 07:27:38',
                'updated_at' => '2018-10-26 07:27:38',
            ),
            
            array (
                'id' => 35571537961651,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Organizatori',
                'model_name' => 'Organizatori',
                'table_name' => 'promoters',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-bullhorn',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-09-26 09:34:11',
                'updated_at' => '2018-10-03 09:14:19',
            ),
            
            array (
                'id' => 35631542790824,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Web strane',
                'model_name' => 'WebStrane',
                'table_name' => 'pages',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-bookmark-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-11-21 09:00:24',
                'updated_at' => '2018-11-27 09:31:02',
            ),
            
            array (
                'id' => 36291538481832,
                'category' => NULL,
                'type' => 'sortable',
                'name' => 'Udruzenja',
                'model_name' => 'Udruzenja',
                'table_name' => 'associations',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-users',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-10-02 10:03:52',
                'updated_at' => '2018-12-04 11:59:31',
            ),
            
            array (
                'id' => 36651540538747,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Brojevi telefona',
                'model_name' => 'BrojeviTelefona',
                'table_name' => 'phone_numbers',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{phone_number}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-phone',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-10-26 07:25:47',
                'updated_at' => '2018-10-26 07:25:47',
            ),
        ));
        
        
    }
}