<?php

use Illuminate\Database\Seeder;

class ModulesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('modules')->delete();
        
        \DB::table('modules')->insert(array (
            
            array (
                'id' => 1,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Users',
                'model_name' => 'User',
                'table_name' => 'users',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{first_name}} {{last_name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-users',
                'reporting' => 1,
                'lazy_loading' => 0,
                'is_system' => 1,
                'created_at' => '2016-04-01 09:17:48',
                'updated_at' => '2018-03-04 14:57:04',
            ),
            
            array (
                'id' => 2,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Invitations',
                'model_name' => 'Invitations',
                'table_name' => 'invitations',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{email}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-envelope-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'created_at' => '2016-08-18 08:10:56',
                'updated_at' => '2016-08-18 08:10:56',
            ),
            
            array (
                'id' => 3,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Invitation Statuses',
                'model_name' => 'InvitationStatuses',
                'table_name' => 'invitation_statuses',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-list',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'created_at' => '2016-08-18 12:18:07',
                'updated_at' => '2016-08-18 12:18:07',
            ),
            
            array (
                'id' => 4,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Assets',
                'model_name' => 'Assets',
                'table_name' => 'assets',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{file_name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-file-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            
            array (
                'id' => 5,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Roles',
                'model_name' => 'Roles',
                'table_name' => 'roles',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-user-circle-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'created_at' => '2016-09-02 12:24:28',
                'updated_at' => '2016-09-02 12:24:28',
            ),
            
            array (
                'id' => 6,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Permissions',
                'model_name' => 'Permissions',
                'table_name' => 'permissions',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-minus-circle',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'created_at' => '2016-09-02 12:43:44',
                'updated_at' => '2016-09-02 12:43:44',
            ),
            
            array (
                'id' => 7,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'File Tags',
                'model_name' => 'FileTags',
                'table_name' => 'file_tags',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-tags',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'created_at' => '2016-10-07 07:14:34',
                'updated_at' => '2016-10-07 07:14:34',
            ),
            
            array (
                'id' => 8,
                'category' => 0,
                'type' => 'sortable',
                'name' => 'Widgets',
                'model_name' => 'Widgets',
                'table_name' => 'widgets',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-square',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'created_at' => '2018-01-10 22:23:31',
                'updated_at' => '2018-01-11 08:18:51',
            ),
            
            array (
                'id' => 9,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Resized Images',
                'model_name' => 'ResizedImages',
                'table_name' => 'resized_images',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{top_x}},{{top_y}} - {{height}},{{width}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-picture-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'created_at' => '2017-06-13 06:41:12',
                'updated_at' => '2017-06-13 06:41:12',
            ),
            
            array (
                'id' => 10,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Image sizes',
                'model_name' => 'ImageSizes',
                'table_name' => 'image_sizes',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-picture-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            ),
            
            array (
                'id' => 12,
                'category' => NULL,
                'type' => 'multilevel_sortable',
                'name' => 'Galleries',
                'model_name' => 'Galleries',
                'table_name' => 'galleries',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{id}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-camera',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'created_at' => '2017-08-20 16:32:56',
                'updated_at' => '2017-08-20 16:32:56',
            ),
            
            array (
                'id' => 13,
                'category' => 12,
                'type' => 'multilevel_sortable',
                'name' => 'Gallery Items',
                'model_name' => 'GalleryItems',
                'table_name' => 'gallery_items',
                'max_depth' => 0,
                'slug' => NULL,
                'anchor_text' => '{{id}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-camera',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'created_at' => '2017-08-20 16:33:27',
                'updated_at' => '2017-08-20 16:33:27',
            ),
            
            array (
                'id' => 32791524315581,
                'category' => 0,
                'type' => 'non_sortable',
                'name' => 'Test13',
                'model_name' => 'Test13',
                'table_name' => 'test13',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'created_at' => '2018-04-21 12:59:41',
                'updated_at' => '2018-04-21 12:59:41',
            ),
            
            array (
                'id' => 32951524315898,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Test 17',
                'model_name' => 'Test17',
                'table_name' => 'test_17',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'created_at' => '2018-04-21 13:04:58',
                'updated_at' => '2018-04-21 13:04:58',
            ),
            
            array (
                'id' => 33121524316238,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Test 18',
                'model_name' => 'Test18',
                'table_name' => 'test_18',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'created_at' => '2018-04-21 13:10:38',
                'updated_at' => '2018-04-21 13:10:38',
            ),
            
            array (
                'id' => 33251524313637,
                'category' => 0,
                'type' => 'non_sortable',
                'name' => 'Test 2',
                'model_name' => 'Test2',
                'table_name' => 'test_2',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{id}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'created_at' => '2018-04-21 12:27:17',
                'updated_at' => '2018-04-21 12:27:17',
            ),
            
            array (
                'id' => 33411524315683,
                'category' => 0,
                'type' => 'non_sortable',
                'name' => 'Test14',
                'model_name' => 'Test14',
                'table_name' => 'test14',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'created_at' => '2018-04-21 13:01:23',
                'updated_at' => '2018-04-21 13:01:23',
            ),
            
            array (
                'id' => 33931524314828,
                'category' => 0,
                'type' => 'non_sortable',
                'name' => 'Test 11',
                'model_name' => 'Test11',
                'table_name' => 'test_11',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{id}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'created_at' => '2018-04-21 12:47:08',
                'updated_at' => '2018-04-21 12:47:08',
            ),
            
            array (
                'id' => 34021524315842,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Test 16',
                'model_name' => 'Test16',
                'table_name' => 'test_16',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'created_at' => '2018-04-21 13:04:02',
                'updated_at' => '2018-04-21 13:04:02',
            ),
            
            array (
                'id' => 34601524652876,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Articles',
                'model_name' => 'Articles',
                'table_name' => 'articles',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'created_at' => '2018-04-25 10:41:16',
                'updated_at' => '2018-04-25 10:41:16',
            ),
            
            array (
                'id' => 34671520174290,
                'category' => 0,
                'type' => 'non_sortable',
                'name' => 'Social Login IDs',
                'model_name' => 'SocialLoginIds',
                'table_name' => 'social_login_ids',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{social_id}} - {{adapter_name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-id-card-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'created_at' => '2018-03-04 14:38:10',
                'updated_at' => '2018-03-04 14:38:10',
            ),
            
            array (
                'id' => 34881524313609,
                'category' => 0,
                'type' => 'non_sortable',
                'name' => 'Test',
                'model_name' => 'Test',
                'table_name' => 'test',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{id}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'created_at' => '2018-04-21 12:26:49',
                'updated_at' => '2018-04-21 12:26:49',
            ),
            
            array (
                'id' => 35181524315504,
                'category' => 0,
                'type' => 'non_sortable',
                'name' => 'Test12',
                'model_name' => 'Test12',
                'table_name' => 'test12',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{id}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'created_at' => '2018-04-21 12:58:24',
                'updated_at' => '2018-04-21 12:58:24',
            ),
            
            array (
                'id' => 35321524315804,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Test 15',
                'model_name' => 'Test15',
                'table_name' => 'test_15',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'created_at' => '2018-04-21 13:03:24',
                'updated_at' => '2018-04-21 13:03:24',
            ),
            
            array (
                'id' => 35691524316607,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Test 20',
                'model_name' => 'Test20',
                'table_name' => 'test_20',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-trophy',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'created_at' => '2018-04-21 13:16:47',
                'updated_at' => '2018-04-21 13:16:47',
            ),
            
            array (
                'id' => 36791524316270,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Test 19',
                'model_name' => 'Test19',
                'table_name' => 'test_19',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-bars',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'created_at' => '2018-04-21 13:11:10',
                'updated_at' => '2018-04-21 13:11:10',
            ),
        ));
        
        
    }
}