<?php

namespace Photon\PhotonCms\Core\Database\Seeds\InitialCore;

use Illuminate\Database\Seeder;

class ImageSizesModuleSeeder extends Seeder
{
    public function run()
    {
        // Modules
        \DB::table('modules')->insert(array (
            array (
                'id' => 10,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Image sizes',
                'model_name' => 'ImageSizes',
                'table_name' => 'image_sizes',
                'max_depth' => NULL,
                'anchor_text' => '{{name}}',
                'icon' => 'fa fa-picture-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            )
        ));

        // Fields
        \DB::table('fields')->insert(array (
            array (
                'type' => 1,
                'name' => 'Name',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'name',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image size name.',
                'validation_rules' => 'required|string',
                'module_id' => 10,
                'order' => 0,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            ),

            array (
                'type' => 10,
                'name' => 'Width',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'width',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image width.',
                'validation_rules' => 'integer',
                'module_id' => 10,
                'order' => 1,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            ),

            array (
                'type' => 10,
                'name' => 'Height',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'height',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image height.',
                'validation_rules' => 'integer',
                'module_id' => 10,
                'order' => 2,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            ),

            array (
                'type' => 4,
                'name' => 'Lock width',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'lock_width',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image lock width.',
                'validation_rules' => 'boolean',
                'module_id' => 10,
                'order' => 3,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            ),

            array (
                'type' => 4,
                'name' => 'Lock height',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'lock_height',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image lock height.',
                'validation_rules' => 'boolean',
                'module_id' => 10,
                'order' => 4,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            ),
        ));
    }
}
